apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-qque
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-79-tenant/test-rhtap-79-app/devfile-sample-code-with-quarkus-qque@sha256:6ed6229bb37ada598e808542b8155d9bd1f75225c94cdb850d148fb4706a8510
        name: my-java-quarkus
        resources: {}
status: {}
